import { Inter } from 'next/font/google'
import './globals.css'
import Sightbar from './components/sightbar/Sightbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Sightbar/>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
